package com.mycompany.projetoltp;
// Generated 07/05/2019 11:24:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aluno generated by hbm2java
 */
@Entity
@Table(name="aluno"
    ,catalog="projecao"
)
public class Aluno  implements java.io.Serializable {


     private Integer idAluno;
     private Pessoa pessoa;
     private Integer semestre;
     private Set<Turma> turmas = new HashSet<Turma>(0);

    public Aluno() {
    }

	
    public Aluno(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Aluno(Pessoa pessoa, Integer semestre, Set<Turma> turmas) {
       this.pessoa = pessoa;
       this.semestre = semestre;
       this.turmas = turmas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAluno", unique=true, nullable=false)
    public Integer getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(Integer idAluno) {
        this.idAluno = idAluno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPessoa", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="semestre")
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="aluno_turma", catalog="projecao", joinColumns = { 
        @JoinColumn(name="idAluno", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idTurma", nullable=false, updatable=false) })
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }




}


