package com.mycompany.projetoltp;
// Generated 07/05/2019 11:24:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="projecao"
)
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nome;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Departamento() {
    }

    public Departamento(String nome, Set<Curso> cursos) {
       this.nome = nome;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDepartamento", unique=true, nullable=false)
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


