package com.mycompany.projetoltp;
// Generated 07/05/2019 11:24:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="genero"
    ,catalog="projecao"
)
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String descricao;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Genero() {
    }

	
    public Genero(String descricao) {
        this.descricao = descricao;
    }
    public Genero(String descricao, Set<Pessoa> pessoas) {
       this.descricao = descricao;
       this.pessoas = pessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGenero", unique=true, nullable=false)
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genero")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


