package com.mycompany.projetoltp;
// Generated 07/05/2019 11:24:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,catalog="projecao"
)
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private Genero genero;
     private String nome;
     private String sobrenome;
     private String matricula;
     private Date dataNascimento;
     private Date dataIngresso;
     private String email;
     private String usuario;
     private String senha;
     private Set<Professor> professors = new HashSet<Professor>(0);
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);
     private Set<Aluno> alunos = new HashSet<Aluno>(0);

    public Pessoa() {
    }

    public Pessoa(Genero genero, String nome, String sobrenome, String matricula, Date dataNascimento, Date dataIngresso, String email, String usuario, String senha, Set<Professor> professors, Set<Endereco> enderecos, Set<Aluno> alunos) {
       this.genero = genero;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.matricula = matricula;
       this.dataNascimento = dataNascimento;
       this.dataIngresso = dataIngresso;
       this.email = email;
       this.usuario = usuario;
       this.senha = senha;
       this.professors = professors;
       this.enderecos = enderecos;
       this.alunos = alunos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPessoa", unique=true, nullable=false)
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGenero")
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sobrenome", length=45)
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    
    @Column(name="matricula", length=45)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataIngresso", length=10)
    public Date getDataIngresso() {
        return this.dataIngresso;
    }
    
    public void setDataIngresso(Date dataIngresso) {
        this.dataIngresso = dataIngresso;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="senha", length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Professor> getProfessors() {
        return this.professors;
    }
    
    public void setProfessors(Set<Professor> professors) {
        this.professors = professors;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pessoa_endereco", catalog="projecao", joinColumns = { 
        @JoinColumn(name="Pessoa_idPessoa", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Endereco_idEndereco", nullable=false, updatable=false) })
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    public Set<Aluno> getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set<Aluno> alunos) {
        this.alunos = alunos;
    }




}


